export const products = [
    {
        id: 1,
        title:"Collares Scom",
        price: 2000,
        stock: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet.",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768376/reactjs%20coderhouse/accesorios1_qpzv8h.png",
    },
    {
        id: 2,
        title:"Collar Heart",
        price: 1600,
        stock: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet.",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768385/reactjs%20coderhouse/accesorios2_g7a8z6.png",
    },
    {
        id: 3,
        title:"Piluso radiate positivity",
        price: 4000,
        stock: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet.",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768393/reactjs%20coderhouse/accesorios3_sqx9mr.png",
    },
    {
        id: 4,
        title:"Piluso heladito",
        price: 4000,
        stock: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet.",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768402/reactjs%20coderhouse/accesorios4_j8vcge.png",
    },
    {
        id: 5,
        title:"Paleta Dreamy",
        price: 2400,
        stock: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet.",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769382/reactjs%20coderhouse/maquillaje1_qm8ahh.png",
    },
    {
        id: 6,
        title:"Paleta Lucky",
        price: 2800,
        stock: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet.",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769393/reactjs%20coderhouse/maquillaje2_aespll.png",
    },
    {
        id: 7,
        title:"Ink velvet 01",
        price: 1800,
        stock: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet.",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769409/reactjs%20coderhouse/maquillaje3_tbjmpn.png",
    },
    {
        id: 8,
        title:"Ink velvet 32",
        price: 1800,
        stock: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor magna sit amet semper commodo. Sed a suscipit lorem. Vestibulum bibendum risus sit amet lacinia euismod. Curabitur ac ligula in risus feugiat aliquet. ",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769429/reactjs%20coderhouse/maquillaje4_fzolxf.png",
    },
]