export const products = [
    {
        id: 1,
        title:"collares perlas y lentejuelas",
        price: 2000,
        stock: 10,
        description: "Set dos collares de perlas y lentejuelas",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768376/reactjs%20coderhouse/accesorios1_qpzv8h.png",
    },
    {
        id: 2,
        title:"collar dije corazon",
        price: 1600,
        stock: 10,
        description: "Collar mitad de lentejuelas y perlas con dije de corazon",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768385/reactjs%20coderhouse/accesorios2_g7a8z6.png",
    },
    {
        id: 3,
        title:"piluso radiate positivity",
        price: 4000,
        stock: 10,
        description: "Piluso de tela con bordado frontal",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768393/reactjs%20coderhouse/accesorios3_sqx9mr.png",
    },
    {
        id: 4,
        title:"piluso heladito",
        price: 4000,
        stock: 10,
        description: "Piluso de tela con bordado frontal",
        category:"accesorios",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681768402/reactjs%20coderhouse/accesorios4_j8vcge.png",
    },
    {
        id: 5,
        title:"paleta de sombras dreamy",
        price: 2400,
        stock: 10,
        description: "Paleta de sombras para ojos, con vitamina E, contiene 9 tonalidades",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769382/reactjs%20coderhouse/maquillaje1_qm8ahh.png",
    },
    {
        id: 6,
        title:"paleta de sombras lucky",
        price: 2800,
        stock: 10,
        description: "Paleta de sombras de larga duración e intrasferibles con Vitamina E, contiene 10 tonalidades",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769393/reactjs%20coderhouse/maquillaje2_aespll.png",
    },
    {
        id: 7,
        title:"ink velvet 01",
        price: 1800,
        stock: 10,
        description: "Tinta para labios de acabado matte y larga duración",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769409/reactjs%20coderhouse/maquillaje3_tbjmpn.png",
    },
    {
        id: 8,
        title:"ink velvet 32",
        price: 1800,
        stock: 10,
        description: "Tinta para labios de acabado matte y larga duración",
        category:"maquillaje",
        img: "https://res.cloudinary.com/dzyku6fye/image/upload/v1681769429/reactjs%20coderhouse/maquillaje4_fzolxf.png",
    },
]